>>> make mypy
  ‚óè Executing mypy in enrobie..
enrobie/plugins/ainswer/plugin.py:94: error: Unexpected keyword argument "api_key"  [call-arg]
.venv-develop/lib/python3.12/site-packages/pydantic_ai/models/anthropic.py:114: note: Called function defined here
enrobie/plugins/ainswer/plugin.py:105: error: Unexpected keyword argument "api_key"  [call-arg]
.venv-develop/lib/python3.12/site-packages/pydantic_ai/models/openai.py:108: note: Called function defined here
